### ISSUE TITLE
.rspec config looks ignored even in Regular Mode

### ISSUE THREAD

**Issue by tnir** [KnapsackPro/knapsack#102]
`.rspec` config looks ignored even in Regular Mode (with knapsack_pro Gem, or with knapsack Gem) while `knapsack_pro` gem docs shows (only) Queue Mode ignore `.rspec` config: https://github.com/KnapsackPro/knapsack_pro-ruby/commit/321de44d51b438a250a57575e79de90ca0d33ec4

**Comment by ArturT** [comment]
Hi @tnir 

`knapsack_pro` gem in [Regular Mode uses a rake task to start RSpec](https://github.com/KnapsackPro/knapsack_pro-ruby/blob/f8f315010bf7683d7965efdc5272e53a2f53e137/lib/knapsack_pro/runners/rspec_runner.rb#L21,L28) process. RSpec reads `.rspec` file. I've just tested it now to double check and I confirm the `.rspec` flags are respected for RSpec in knapsack_pro Regular Mode.


In knapsack_pro Queue Mode the [RSpec is started via `RSpec::Core::Runner`](https://github.com/KnapsackPro/knapsack_pro-ruby/blob/f8f315010bf7683d7965efdc5272e53a2f53e137/lib/knapsack_pro/runners/queue/rspec_runner.rb#L85) class and then `.rspec` file is not respected by the RSpec. You need to pass arguments manually as described here
https://knapsackpro.com/faq/question/why-when-i-use-queue-mode-for-rspec-then-rspec-config-is-ignored


In `knapsack` gem the [RSpec process is started via shell command](https://github.com/KnapsackPro/knapsack/blob/d9abb662f6a5d5473c34af4d63ccdd077ee14935/lib/knapsack/runners/rspec_runner.rb#L15) so the `.rspec` file should be respected. 

You can learn more about how `knapsack_pro` works in [Regular Mode vs Queue Mode](https://docs.knapsackpro.com/2020/how-to-speed-up-ruby-and-javascript-tests-with-ci-parallelisation).

**Comment by tnir** [comment]
@ArturT Thanks!
