### ISSUE TITLE
Knapsack doesn't work with spring binstubs

### ISSUE THREAD

**Issue by synth** [KnapsackPro/knapsack#54]
Our app has binstubs generated by rails/spring in the application root/bin folder. So for example, here is Rails.root/bin/rspec

    #!/usr/bin/env ruby
    begin
      load File.expand_path('../spring', __FILE__)
    rescue LoadError => e
      raise unless e.message.include?('spring')
    end
    require 'bundler/setup'
    load Gem.bin_path('rspec-core', 'rspec')

So, we execute all commands with the bin/ prefix. 

    bin/rspec spec
    bin/rails c

When we run knapsack

    bundle exec knapsack:rspec

We get loads of errors, including `undefined_method` errors

How can we get Knapsack to play nice with our binstubs?

**Comment by ArturT** [comment]
I saw you forked the gem https://github.com/synth/knapsack/commit/884069ccbdfc925fa81836e3a750efd4e2e41fb0
Does it solve your problem?

**Comment by synth** [comment]
Yes, it solves it temporarily. Perhaps the rspec command can be parameterized.

**Comment by ArturT** [comment]
In knapsack_pro gem I load the rspec task in a bit different way:
https://github.com/KnapsackPro/knapsack_pro-ruby/blob/master/lib/knapsack_pro/runners/rspec_runner.rb

You may want to try the knapsack_pro gem to see if it works better for you.

**Comment by ibrahima** [comment]
is it possible to try knapsack_pro (just to see if it fixes the issue) without getting a license for it? Why doesn't knapsack free use the same way of loading rake tasks? It'd be nice to make sure that the free version works with spring binstubs too, since it's a fairly common thing.

(I'm having a similar issue and am trying @synth's fork, but it'd be nice to not have to do that)

**Comment by ArturT** [comment]
Hi @ibrahima 

> is it possible to try knapsack_pro (just to see if it fixes the issue) without getting a license for it?

Sure you can try https://knapsackpro.com for free. The trial is 14 days and days are count only when you use Knapsack Pro API. If you need more time to test it please just drop me an email so I will extend your trial period.

> Why doesn't knapsack free use the same way of loading rake tasks?

[knapsack](https://github.com/ArturT/knapsack/) gem is older project than [knapsack_pro](https://github.com/KnapsackPro/knapsack_pro-ruby) hence the differences.

**Comment by ibrahima** [comment]
Ah OK, that still didn't resolve my issue, so I think my problem is unrelated to binstubs. I'll open a new issue then.

**Comment by 3v0k4** [comment]
We officially archived Knapsack, you can read more about it [here](https://knapsackpro.com/knapsack_gem).

Thank you for caring and creating this issue.

I'm sorry we couldn't get this done for you.
