### ISSUE TITLE
How can this be used with the Kubernetes Jenkins Plugin that dynamically creates Jenkins slaves

### ISSUE THREAD

**Issue by dbwest** [KnapsackPro/knapsack#81]
I need to know if anyone has a documented solution for using this with the Kubernetes plugin for Jenkins.

**Comment by ArturT** [comment]
The only example about Jenkins I have from one of the customers. You can take a look at this:
https://github.com/KnapsackPro/knapsack_pro-ruby#info-for-jenkins-users

**Comment by 3v0k4** [comment]
We officially archived Knapsack, you can read more about it [here](https://knapsackpro.com/knapsack_gem).

Thank you for caring and creating this issue.

I'm sorry we couldn't get this done for you.
